language: java

jdk:
- openjdk11

before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
- export JAVA_HOME=$HOME/openjdk11
- $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME

os:
- linux

install:
  gradle

