language: java

jdk:
- openjdk11

before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
- export JAVA_HOME=$HOME/openjdk11
- chmod +x $TRAVIS_BUILD_DIR/install-jdk.sh
- $TRAVIS_BUILD_DIR/install-jdk.sh -F 11 -L GPL

os:
- linux


