= *Planet API*

image:https://api.codacy.com/project/badge/Grade/78f9b8b12c154d27b7e5c9c3ceff438e[link="https://app.codacy.com/app/luizinhoab/planet-api?utm_source=github.com&utm_medium=referral&utm_content=luizinhoab/planet-api&utm_campaign=Badge_Grade_Dashboard"]

image:https://img.shields.io/badge/vert.x-3.6.3-purple.svg[link="https://vertx.io"]

The purpose of this application was the challenge participation proposed by B2W hiring team.is api was specified and documented under Open API 3 standard.


This application exposes a reactive rest microservice, under Java/Vert.x,docker-mongo with crud operations to handle planets persited on MongoDb.


== *Running*

Will need install http://jdk.java.net/11/[OpenJDK 11] and https://gradle.org/[Gradle 5.2] to build and run the app.

=== _Development_ :

===== Intelij

  Main Class: io.vertx.core.Launcher
  VM Options:
    -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory
    --add-exports
    java.base/jdk.internal.misc=ALL-UNNAMED
    -Dio.netty.tryReflectionSetAccessible=true
  Program arguments: run io.starwars.planet.PlanetAPIVerticle -conf src/main/resources/conf/config-dev.json

===== Gradle

  ./gradlew clean run

=== __Test __ :

==== Unit

    ./gradlew clean test

==== Integration

    ./gradlew clean integrationTest

=== _Production_ :

===== Packaging

    ./gradlew clean shadowJar

===== Start application

    java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory
         --add-exports java.base/jdk.internal.misc=ALL-UNNAMED
         -Dio.netty.tryReflectionSetAccessible=true
         -jar -conf src/main/resources/conf/config-dev.json

== *Help*

* https://vertx.io/docs/[Vert.x Documentation]
* https://swagger.io/[Open API 3]


