= *Planet API*

image:https://travis-ci.org/luizinhoab/planet-api.svg?branch=master["Build Status", link="https://travis-ci.org/luizinhoab/planet-api"] image:https://api.codacy.com/project/badge/Grade/78f9b8b12c154d27b7e5c9c3ceff438e[link="https://app.codacy.com/app/luizinhoab/planet-api?utm_source=github.com&utm_medium=referral&utm_content=luizinhoab/planet-api&utm_campaign=Badge_Grade_Dashboard"] image:https://api.codacy.com/project/badge/Coverage/45aedff8bba941d1bee2d87b435df72c["Codacy code quality", link="https://www.codacy.com/app/luizinhoab/planet-api?utm_source=github.com&utm_medium=referral&utm_content=luizinhoab/planet-api&utm_campaign=Badge_Coverage"]

image:https://img.shields.io/badge/vert.x-3.6.3-purple.svg[link="https://vertx.io"]


The purpose of this application was the challenge participation proposed by B2W hiring team.This api was specified and documented under Open API 3 standard and can be consulted on https://app.swaggerhub.com/apis-docs/luizinhoab/b2w-challenge/1.0.0[https://app.swaggerhub.com/apis-docs/luizinhoab/b2w-challenge/1.0.0] .


This application exposes a reactive rest microservice, under Java/Vert.x, with crud operations to handle planets persited on MongoDb.


== *Running*

Will need install http://jdk.java.net/11/[OpenJDK 11] and https://gradle.org/[Gradle 5.2] to build and run the app.
Optionally install https://www.docker.com/[Docker] to run the container with MongoDb and sample data loaded, is same image used in the integration tests.

=== _Development_ :

===== Sample Database

  docker build -t mongo-test . && docker run -p 0.0.0.0:27016:27016 --name mongo-dev -d  -t  -i  mongo-test

===== Intelij

  Main Class: io.vertx.core.Launcher
  VM Options:
    -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory
    --add-exports
    java.base/jdk.internal.misc=ALL-UNNAMED
    -Dio.netty.tryReflectionSetAccessible=true
  Program arguments: run io.starwars.planet.PlanetAPIVerticle -conf src/main/resources/conf/config-dev.json

===== Gradle

  ./gradlew clean run

=== __Test __ :

==== Unit

    ./gradlew clean test

==== Integration

    ./gradlew clean integrationTest

==== Check

Run complete verification, currently unit and integration tests, runned by Travis.

    ./gradlew clean check

=== _Production_ :

===== Packaging

    ./gradlew clean shadowJar

===== Start application

    java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory
         --add-exports java.base/jdk.internal.misc=ALL-UNNAMED
         -Dio.netty.tryReflectionSetAccessible=true
         -jar plane-api-<VERSION>.jar -conf src/main/resources/conf/config-dev.json

== *Built with*

* http://jdk.java.net/11/[OpenJDK 11] - Java 11
* https://vertx.io/[Vert.x] - Eclipse Vert.x is a tool-kit for building reactive applications on the JVM.
* https://swagger.io/[Open API 3] - Design API
* https://gradle.org/[Gradle] Dependency management and tasks automatization
